version: 3

tasks:
  front:install:
    dir: frontend
    cmds:
      - pnpm install
  front:check:
    dir: frontend
    cmds:
      - pnpm run check
  front:check:ci:
    dir: frontend
    cmds:
      - pnpm run check:ci
  front:format:
    dir: frontend
    cmds:
      - pnpm format
  front:lint:
    dir: frontend
    cmds:
      - pnpm lint
  go:test:unit:
    cmds:
      - go test -v ./test/...
  go:build:
    cmds:
      - wails build
  front:test:unit:
    dir: frontend
    cmds:
      - pnpm test:unit
  front:test:e2e:
    dir: frontend
    cmds:
      - pnpm test:e2e
  front:vitest:
    dir: frontend
    cmds:
      - pnpm vitest
  front:build:
    dir: frontend
    cmds:
      - pnpm build
  front:check:bundle:
    dir: frontend
    cmds:
      - pnpm run check:bundle
  front:update:
    dir: frontend
    cmds:
      - pnpm update -L
  dev:
    cmds:
      - wails dev -s -skipbindings
  go:update:
    cmds:
      - go get -u .
  gen-module:
    cmds:
      - wails generate module
