// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Auth(arg1) {
  return window['go']['syncs']['DBXSync']['Auth'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['syncs']['DBXSync']['DownloadFile'](arg1);
}

export function GetAuthURL() {
  return window['go']['syncs']['DBXSync']['GetAuthURL']();
}

export function GetMetadata(arg1) {
  return window['go']['syncs']['DBXSync']['GetMetadata'](arg1);
}

export function GetTemporaryLink(arg1) {
  return window['go']['syncs']['DBXSync']['GetTemporaryLink'](arg1);
}

export function IsAuthenticated() {
  return window['go']['syncs']['DBXSync']['IsAuthenticated']();
}

export function UploadFile(arg1) {
  return window['go']['syncs']['DBXSync']['UploadFile'](arg1);
}

export function UploadRawFile(arg1) {
  return window['go']['syncs']['DBXSync']['UploadRawFile'](arg1);
}
