// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportBundle() {
  return window['go']['exporter']['Exporter']['ExportBundle']();
}
