// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoExport(arg1) {
  return window['go']['exporter']['Exporter']['AutoExport'](arg1);
}

export function ExportBundle() {
  return window['go']['exporter']['Exporter']['ExportBundle']();
}

export function SelectFolder() {
  return window['go']['exporter']['Exporter']['SelectFolder']();
}
