// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoExport(arg1:string):Promise<void>;

export function ExportBundle():Promise<void>;

export function SelectFolder():Promise<string>;
