// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Auth(arg1) {
  return window['go']['sync']['DBXSync']['Auth'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['sync']['DBXSync']['DownloadFile'](arg1);
}

export function GetMetadata(arg1) {
  return window['go']['sync']['DBXSync']['GetMetadata'](arg1);
}

export function IsAuthenticated() {
  return window['go']['sync']['DBXSync']['IsAuthenticated']();
}

export function UploadFile(arg1) {
  return window['go']['sync']['DBXSync']['UploadFile'](arg1);
}
