// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sync} from '../models';

export function Auth(arg1:string):Promise<void>;

export function DownloadFile(arg1:string):Promise<sync.Result>;

export function GetMetadata(arg1:string):Promise<sync.MetadataResult>;

export function IsAuthenticated():Promise<boolean>;

export function UploadFile(arg1:sync.UploadArgs):Promise<sync.UploadResult>;
