// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExcludeLocal(arg1) {
  return window['go']['saveload']['SaveLoad']['ExcludeLocal'](arg1);
}

export function LoadLocal(arg1) {
  return window['go']['saveload']['SaveLoad']['LoadLocal'](arg1);
}

export function SaveAnyLocal(arg1, arg2) {
  return window['go']['saveload']['SaveLoad']['SaveAnyLocal'](arg1, arg2);
}

export function SaveLocal(arg1, arg2) {
  return window['go']['saveload']['SaveLoad']['SaveLocal'](arg1, arg2);
}
