// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadLocal(arg1:string):Promise<string>;

export function SaveAnyLocal(arg1:string,arg2:any):Promise<void>;

export function SaveLocal(arg1:string,arg2:string):Promise<void>;
