name: 🏷️ Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: 📦 Release executables
    environment: prd
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      VITE_DBX_CLIENT_ID: ${{ secrets.VITE_DBX_CLIENT_ID }}
      VITE_VERSION: ${{ github.ref_name}}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: ./.github/workflows/base-setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build
        run: task go:build
            
      - name: Upload binary
        uses: softprops/action-gh-release@v1
        with:
          files: build/bin/script-writing.exe